Completed implementation of technical documentation and API documenta…
jacobtime/HealthCode pull request #2
Opened 2024-07-09 09:59 UTC by cx229

Completed implementation of technical documentation and API documentation functionality

2024-07-09 14:26 UTC, jacobtime requested changes

2024-07-09 14:26 UTC, jacobtime commented on place-code/src/main/java/org/software/code/mapper/PlaceMappingMapper.java
> +    @Insert("INSERT INTO place_mapping (pid, uid, time) VALUES (#{pid}, #{uid}, #{time})")
场所码微服务只有根据pid找出所有的人，没有这个吧？

2024-07-09 14:26 UTC, jacobtime commented on pom.xml
> -            <version>${spring-boot.version}</version>
全局统一的版本不应该自己自定义

2024-07-09 14:26 UTC, jacobtime commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    public void init() {
单独提出来作为util

2024-07-09 14:26 UTC, jacobtime commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    private String getOpenIDFromWX(String code) {
这个可以mock，也不是放到service

2024-07-09 14:26 UTC, jacobtime commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    public void testhhh(String hhh) {
🤔

2024-07-17 01:18 UTC, cx229 commented on health-code/src/main/java/org/software/code/controller/HealthCodeInternalController.java
> +        return Result.success("");// 技术文档未说明出参
已修改

2024-07-17 01:18 UTC, cx229 commented on health-code/pom.xml
> +            <artifactId>mysql-connector-java</artifactId>
已删除

2024-07-17 01:20 UTC, cx229 commented on health-code/src/main/java/org/software/code/client/HealthCodeClient.java
>  public interface HealthCodeClient {
管理人员调用转码是健康码微服务的，直接使用service，没使用client

2024-07-17 01:25 UTC, cx229 commented on place-code/src/main/java/org/software/code/mapper/PlaceMappingMapper.java
> +    @Insert("INSERT INTO place_mapping (pid, uid, time) VALUES (#{pid}, #{uid}, #{time})")
扫描场所码时，会插入数据

2024-07-17 01:26 UTC, cx229 commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    public void init() {
已修改

2024-07-17 01:26 UTC, cx229 commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    public void testhhh(String hhh) {
已删除测试代码

2024-07-17 01:26 UTC, cx229 commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    private String getOpenIDFromWX(String code) {
那应该放在？

2024-07-17 01:30 UTC, cx229 commented on pom.xml
> -            <version>${spring-boot.version}</version>
已修改

2024-07-17 14:13 UTC, jacobtime commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    public void init() {
没看到snowflakeUtil.java在common文件夹里面啊？

2024-07-17 14:13 UTC, jacobtime commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    public void init() {
看到了，你应该放到common文件夹里面，包括init这个函数

2024-07-17 14:13 UTC, jacobtime commented on user/src/main/java/org/software/code/service/Impl/UserServiceImpl.java
> +    private String getOpenIDFromWX(String code) {
单独一个文件在common里面

2024-07-17 14:13 UTC, jacobtime commented on pom.xml
> -            <version>${spring-boot.version}</version>
怎么没看到改动？

2024-07-17 14:13 UTC, jacobtime commented on pom.xml
> -            <version>${spring-boot.version}</version>
你注释掉的代码是正确的，你留着的是要改的

2024-07-17 14:43 UTC, jacobtime commented on health-code/src/main/java/org/software/code/controller/HealthCodeController.java
> +        long uid = healthCodeService.extractUidValidateToken(token);
应该是通过JWTUtil来用token获取uid而不是用service再包装一层

2024-07-17 14:43 UTC, jacobtime commented on health-code/src/main/java/org/software/code/controller/HealthCodeInternalController.java
> +        long uid = healthCodeService.extractUIDValidateQRCodeToken(qrcode_token);
应该用JWTUtil来搞

2024-07-17 14:43 UTC, jacobtime commented on health-code/src/main/java/org/software/code/service/impl/HealthCodeServiceImpl.java
但是微服务的service就不需要单独函数来调JWTUtil了，直接在controller里面调JWTUtil拿到uid、mid、tid然后给service

2024-07-17 14:43 UTC, jacobtime commented on nucleic-acids/src/main/java/org/software/code/controller/NucleicAcidsController.java
> +            return Result.failed((IResult) e);
友好的错误信息

2024-07-17 14:43 UTC, jacobtime commented on nucleic-acids/src/main/java/org/software/code/service/impl/NucleicAcidsServiceImpl.java
> +    public long extractUidValidateToken(String token) {
应该是JWTUtil的功能，后面几个函数也是

2024-07-17 14:43 UTC, jacobtime commented on user/src/main/java/org/software/code/controller/UserController.java
> -@RequestMapping("/user")
你怎么把这个删了？你后面的所有url都不需要user前缀的，还原回来，然后后面的url都不要有/user

2024-07-20 03:33 UTC, jacobtime commented on health-code/src/main/java/org/software/code/common/JWTUtil.java
> +    public String generateJWToken(long id,long expirationTime) {
用静态类

2024-07-20 03:33 UTC, jacobtime commented on itinerary-code/src/main/java/org/software/code/common/JWTUtil.java
> +    public String generateJWToken(long id,long expirationTime) {
静态类

2024-07-20 03:33 UTC, jacobtime commented on nucleic-acids/src/main/java/org/software/code/common/JWTUtil.java
> +    public String generateJWToken(long id,long expirationTime) {
静态类

2024-07-20 03:33 UTC, jacobtime commented on place-code/src/main/java/org/software/code/common/JWTUtil.java
> +    public String generateJWToken(long id,long expirationTime) {
静态类

2024-07-20 03:33 UTC, jacobtime commented on user/src/main/java/org/software/code/common/JWTUtil.java
> +    public String generateJWToken(long id,long expirationTime) {
静态类

2024-07-22 00:17 UTC, jacobtime approved these changes

2024-07-22 00:21 UTC, jacobtime approved these changes

2024-07-22 00:22 UTC, merged